<?xml version="1.0" ?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="M_PI" value="3.1415926"/>
    <xacro:property name="base_mass" value="20"/>
    <xacro:property name="base_length" value="0.40"/>
    <xacro:property name="base_width" value="0.20"/>
    <xacro:property name="base_height" value="0.02"/>
    
    <xacro:property name="wheel_mass" value="2">
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_joint_y" value="0.11"/>
    <xacro:property name="wheel_joint_z" value="0.01"/>
    
    <material name="white">
        <color rgba="1 1 1 0.9"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="blue">
        <color rgba="0 0 1 0.95"/>
    </material>
    
    <!-- 惯性参数与碰撞属性 -->
    <xacro:macro name="box_inertial_matrix" params="m r">
       <inertial>
          <mass value="${m}"/>
          <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}" iyz="0" izz="${2*m*r*r/5}"/>
       </inertial>
    </xacro:macro>
    
    <xacro:macro name="cyliner_inertial_matrix" params="m r h">
       <inertial>
          <mass value="${m}"/>
          <inertia ixx="${m(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
       </inertial>
    </xacro:macro>
    
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect * wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="${prefix}_wheel_link">
          <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
            </geometry>
            <material name="black"/>
          </visual>
          <collision>
             <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
             <geometry>
               <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
             </geometry>
          </collision>
          <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="$-{wheel_length}"/>
       </link>
       
       <gazebo reference="${prefix}_wheel_link">
           <material>Gazebo/Gray</material>
       </gazebo>
       
       <transmission name="${prefix}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint" >
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <xacro:macro name="front">
       <joint name="front_caster_joint" type="fixed">
         <origin xyz="${base_length/2 - 0.05} 0 ${base_height}" rpy="0 0 0"/>
         <parent link="base_link"/>
         <child link="front_caster_link"/>
         <axis xyz="0 1 0"/>
       </joint>

       <link name="front_caster_link">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.015" />
            </geometry>
            <material name="black"/>
          </visual>
          <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="0.015" />
                </geometry>
            </collision>      
            <xacro:box_inertial_matrix  m="${base_mass}" r="${base_width}" />
        </link>
        <gazebo reference="front_caster_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>
    
    <xacro:macro name="back">
       <joint name="back_caster_joint" type="fixed">
         <origin xyz="${-base_length/2 + 0.05} 0 ${base_height}" rpy="0 0 0"/>
         <parent link="base_link"/>
         <child link="back_caster_link"/>
         <axis xyz="0 1 0"/>
       </joint>

       <link name="back_caster_link">
         <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.08 0.1 0.01" />
            </geometry>
            <material name="blue"/>
         </visual>
         <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.08 0.1 0.01" />
                </geometry>
            </collision>      
            <xacro:box_inertial_matrix  m="${base_mass}" r="0.1" />
       </link>
       <gazebo reference="back_caster_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>
    
    <xacro:macro name="mbot_self_gazebo">
       <link name="base_footprint">
            <visual>
               <origin xyz="0 0 0" rpy="0 0 0"/>
               <geometry>
                    <box size="0.001 0.001 0.001"/>
               </geometry>
            </visual>
       </link>
       
       <gazebo reference="base_footprint">
            <turnGravityOff>false</turnGravityOff>
        </gazebo>
       
       <joint name="base_foorprint_joint" type="fixed">
            <orgin xyz="0 0 ${base_length / 2 + base_height}" rpy="0 0 0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
       </joint>
    
       <link name="base_link">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <!--添加物理属性 -->
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <geometry>
              <box size="${base_length} ${base_width} ${base_height}"/>
           </geometry>
        </collision>
        <xacro:box_inertial_matrix m="${base_mass}" r="${base_width}"/>
       </link>
       
       <gazebo reference="base_link">
            <material>Gazebo/Blue</material>
       </gazebo>
       
       <xacro:wheel prefix="left" reflect="-1"/>
       <xacro:wheel prefix="right" reflect="1"/>
       
       <xacro:front />
       <xacro:back />
       
       <gazebo>
          <plugin name="differential_driver_controller" filename="libgazebo_ros_diff_drive.so">
              <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>true</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>true</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <legacyMode>true</legacyMode>
                <leftJoint>left_wheel_joint</leftJoint>
                <rightJoint>right_wheel_joint</rightJoint>
                <wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
                <wheelDiameter>${2*wheel_radius}</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>1.8</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame> 
                <odometryTopic>odom</odometryTopic> 
                <robotBaseFrame>base_footprint</robotBaseFrame>
           </plugin>
       
    </xacro:macro>
    
</robot>
